version: '3.8'

services:

  reg-webapp:
    build:
      context: .
      dockerfile: ./images/webapp.dockerfile
    image: 2byrds/reg-webapp:latest
    healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
        interval: 2s
        timeout: 3s
        retries: 5
        start_period: 8s
    ports:
      - 3000:3000

  keria:
    image: weboftrust/keria:latest
    environment:
        - KERI_AGENT_CORS=1
        - KERI_URL=http://keria:3902
        - PYTHONUNBUFFERED=1
        - PYTHONIOENCODING=UTF-8
    volumes:
        - ./config/keria.json:/keria/config/keri/cf/keria.json
    entrypoint: keria
    command:
        - start
        - --config-dir
        - /keria/config
        - --config-file
        - keria
        - --name
        - agent
    healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:3902/spec.yaml']
        interval: 2s
        timeout: 3s
        retries: 5
        start_period: 2s
    ports:
        - 3901:3901
        - 3902:3902
        - 3903:3903

  reg-server:
    image: 2byrds/reg-server:latest
    ports:
      - 8000:8000
    environment:
      - ENABLE_CORS=true
      # - VERIFIER_AUTHORIZATIONS=http://host.docker.internal:7676/authorizations/
      # - VERIFIER_PRESENTATIONS=http://host.docker.internal:7676/presentations/
      # - VERIFIER_REPORTS=http://host.docker.internal:7676/reports/
    depends_on:
      - verifier
    healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/doc#']
            interval: 2s
            timeout: 3s
            retries: 5
            start_period: 2s

  verifier:
    image: 2byrds/vlei-verifier:latest
    depends_on:
      - witness-demo
      - vlei-server
    ports:
      - 7676:7676
    # volumes:
    #   - './data/verifier:/usr/local/var/keri'

  vlei-server:
    image: 2byrds/vlei:latest
    ports:
      - 7723:7723
    depends_on:
      - witness-demo
    healthcheck:
      test:
          - CMD
          - curl
          - -f
          - http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  witness-demo:
    # container_name: witnesshost
    # hostname: witnesshost
    image: 2byrds/keripy:latest
    tty: true
    volumes:
      - ./config/witness-demo/:/keripy/scripts/keri/cf/main/
    ports:
        - 5642:5642  # witness
        - 5643:5643  # witness
        - 5644:5644  # witness
        - 5645:5645  # witness
        - 5646:5646  # witness
        - 5647:5647  # witness
    entrypoint: kli witness demo
    healthcheck:
                test: ['CMD', 'curl', '-f', 'http://localhost:5642/oobi']
                interval: 2s
                timeout: 3s
                retries: 5
                start_period: 2s

  deps:
    image: alpine
    command: ['echo', 'Dependencies running']
    depends_on:
      vlei-server:
          condition: service_healthy
      keria:
          condition: service_healthy
      witness-demo:
          condition: service_healthy
      reg-server:
          condition: service_healthy
      reg-webapp:
          condition: service_healthy

  dev-deps:
    image: alpine
    command: ['echo', 'Dependencies running']
    depends_on:
      vlei-server:
          condition: service_healthy
      keria:
          condition: service_healthy
      witness-demo:
          condition: service_healthy
      reg-server:
          condition: service_healthy